### ISSUE TITLE
In-world item placement

### ISSUE THREAD

**Issue by Towsty** [brandon3055/BrandonsCore#1]
One of my favorite features from DraconicEvolution is the abilitiy to hit a key and place anything down in the world. Draconic unfortunately does not always fit well with the theme or feel of certain packs. Would it be possible to bring that functionality over to BrandonsCore? May be kind of an odd request, thought I would ask though.

**Comment by brandon3055** [comment]
Actually no thats not a bad idea. At one point i was actually asked if i could make that feature a separate mod but at the time i did not have BrandonsCore. So yes you can expect this to happen in a future update. 

I will leave this issue open as a reminder to myself.

**Comment by Towsty** [comment]
Sounds good, looking forward to it

**Comment by brandon3055** [comment]
If i actually do this it will have to be a separate mod because Brandon's core needs to be able to run in server only mode for server side mods. Which means it cant add any items or blocks to the game.

In 1.9 Draconic Evolution will be much more configurable so you should be able to just disable everything in the entire mod  except for the placable items feature.
